### ISSUE TITLE
[CT-0.99] Big codebox breaks PDF Export

### ISSUE THREAD

**Issue by txe** [giuspen/cherrytree#1012]
Early version CT-0.99, PDF export doesn't split along codebox into several pages, though it works right in pygtk.
Current version CT-0.99, PDF export is hanging on a long codebox, I suppose, it's after last refactoring

**Comment by ForeverRainbow** [comment]
@txe Yes I think this is my fault, I removed the code for splitting long codeboxes and tables I suppose I didn't put it back :p

**Comment by ForeverRainbow** [comment]
Actually I know exactly what this is, codeboxes and tables will try and move themselves to the next page if the current one cannot fit them, I think it should just print a pdf without anything after a too large codebox/table but if it hangs thats even more of a problem

**Comment by giuspen** [comment]
If a table or codebox is too big for a page it can try and start from the subsequent page if it fits but otherwise should split, at least this is what the Pygtk2 version does, supporting also split on N pages. Both the table and codebox make sense to be longer than a page and we don't want to drop data. I'm not understanding if this was working before @ForeverRainbow rework or not. I can also have a look at this just if it was working before please pay me know I don't want to repeat the work of @txe in case I would go back and find it

**Comment by txe** [comment]
I don't know if it worked before.
I'll take a look at this issue, anyway I wanted to make some changes there.

**Comment by giuspen** [comment]
Ok thanks @txe !

**Comment by ForeverRainbow** [comment]
@txe I was going to look at this but if you are, splitting it over multiple pages should be easy because `print` will keep getting called on a printable until it sets `_done` to true so you can just keep printing the bits which are missing as long as you like

**Comment by txe** [comment]
It's too much broken, @ForeverRainbow, can you fix it all and check other things?
- document with one empty node, options: All Tree, Include Node Name. Result: generate 3 pages
- document with 2 empty nodes, options: All Tree, Include Node Name. Result: generate 3 pages, only one name
- document with 2 empty nodes, options: All tree, New Node on New Page. Result: only one page

**Comment by ForeverRainbow** [comment]
I think the pages problem is due to the floating point arithmatic used to calcuate the number of pages. When testing with ~400 nodes it started to get noticable with 3 pages missing (if I switch out `fmod` for `remainder` it produces 100 more pages than needed)

**Comment by giuspen** [comment]
@ForeverRainbow if you are in difficult with this issue don't worry you can pass me the ball and I'll take it from here

**Comment by ForeverRainbow** [comment]
@giuspen I've fixed all the issues above and the problem with page number generation. I am going to have a look later at fixing page breaks since they are still broken (it is only noticeable with a few hundred pages+). Also it seems the python version cannot handle documents of a few thousand or more pages, it gives an error (I assume it runs out of memory or something)

Thanks for the offer tho :)

**Comment by giuspen** [comment]
@ForeverRainbow well done thanks 😉
