### ISSUE TITLE
C++ Bug: Restore Last View (Scroll Position) Within Note

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1086]
When re-opening CherryTree, it is able to remember which node you were previously viewing.  However, it always returns with the content scrolled all the way to the top.  It would be great if it also remembered the "scroll position" within that note, so that when you return, you're looking at the exact spot where you had been previously.  In the case of very long notes, it can prove a bit cumbersome to scroll around & re-locate where you had been previously looking.

Note: OneNote actually remembers the view position of each note individually, so that if you i.e. switch back & forth between two notes, both will always return right back to where you were looking.  This would be even more useful, as it lets you more easily jump back & forth among your content.

**Comment by giuspen** [comment]
This is actually a bug since theoretically should save the cursor position and scroll to the cursor when you re-open the document

**Comment by txe** [comment]
I fixed the first case, restoring cursor/scroll position when a document is reopened.
I'm not sure about restoring cursor/scroll position between node switching, @giuspen,  should we do it?

**Comment by metal450** [comment]
Just a side note of a possibly related issue (not sure if it is, but since you're looking at this related to scroll positions): #961. Almost whenever I "undo," the view jumps to to a very different location, requiring to scroll manually back to where I previously was.

**Comment by giuspen** [comment]
@txe yes in pygtk2 version there is a dictionary that saves the cursor positions of previously visited nodes to restore the scroll. While we are saving to the config.cfg only the last visited node cursor position, it is important that during the session when you go back to a previously visited node you are not losing the scroll position otherwise switching between a set of nodes becomes a pain when you continuously need to manually re-scroll.
