### ISSUE TITLE
C++ Bug: Can't Copy Link & Paste To URL

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1165]
To reproduce in CherryTree 0.99.11 for Linux:

1) In a richtext node, type a URL, i.e. https://www.google.com. Upon pressing space to continue to the next word, it automatically turns blue+underline (to indicate it's a URL)
2) Select the URL & copy
3) Type some more text, i.e. "this is a link"
4) Select the text->Right click->Insert->Link
5) Paste. Nothing can be pasted.

Also, if I open another text editor (i.e. kwrite) and attempt to paste the URL, I cannot.

In order to able to copy the URL, I have to first explicitly right click & "dismiss" (so it's no longer blue & underlined); then it can be successfully copied & pasted elsewhere.

**Comment by ciranus** [comment]
>     4\. Select the text->Right click->Insert->Link

Because the content of the clipboard has changed, and is now "this is a link" (then not a link).
It's a clipboard setting behavior (selected text is pushed to the clipboard).

**Comment by txe** [comment]
@metal450 , it fixed now, thanks!

**Comment by metal450** [comment]
> Because the content of the clipboard has changed, and is now "this is a link"

Incorrect.

> @metal450 , it fixed now

Thanks! :)

**Comment by ciranus** [comment]
We'll see what is exactly fixed.
I can copy links in CT without any problem, but agree not in an external editor. This is what is probably fixed.

However, I confirm the default clipboard behavior which pushed the selected text to the clipboard, then impossible to paste any previous selected URL to edit the link, if "this is a link" text has been pushed to the clipboard, which is logic.

**Comment by ciranus** [comment]
Now fixed in 0.99.12.
Just to keep in mind with KDE clipboard default setting that:

1. middle-click will paste "`This is a link`" text in the insert link panel.
2. right-click>paste will paste the URL link previously pushed to the clipboard.

Then two items simultaneous stored in the clipboard.

I was familiar with the problem reported by metal450, and always used a workaround, but thought it was a gtk/qt clipboard issue.
Good job.
