### ISSUE TITLE
Images management / investigations

### ISSUE THREAD

**Issue by ciranus** [giuspen/cherrytree#1174]
I've been using nixnotes2 in linux for a while, and noticed a major difference with CT: image management.

In nixnotes2, the images are not stored in the database, but in a separate image folder.
I see some advantages:
 1 - adding images does not increase the database size, which grows very rapidly with images;
 2 - easy to find images with search tool;
 3 - possibility to directly browse the images folder with a file manager to find images, and potentially edit them.

With CT, I always hesitate to add snapshots/images because:
1 - I don't know how to search images in CT database;
2 - sqlite database is growing rapidly with images.

As a workaround, I tried to store images outside CT, and drag the image from a file manager to CT to expect the direct creation of a link to the image, but it does not work (no code prepared for) [ [#1163](https://github.com/giuspen/cherrytree/issues/1163) ]
 
I didn't raise this issue earlier because I understood (_long time ago_) that porting CT from gtk2 to 3 should require minimum effort, with no feature difference, and that already existing CT database should hopefully be 100% compatible from gtk2 to 3.

Now, considering current situation:

1 - how is it possible to search for images in CT ?
2 - for a new instance, would it be possible to propose one day an option to either, embed the images in the database, or store images in an images sub-folder ?

**Comment by txe** [comment]
Hi @ciranus , I agree with your point about the database size. That issue is especially acute for sync or backup  when users want to have high-resolution images and scans (also, heavy embed files) in notes   
> how is it possible to search for images in CT ?

What do you mean by searching for images? By name?

> As a workaround, I tried to store images outside CT, and drag the image from a file manager to CT to expect the direct creation of a link to the image, but it does not work (no code prepared for)

It is unclear what you want. A link to a image file (without showing a picture) or an image in a note? Or as I will suggest later  `a new widget LinkToImage which behaves like a link to an image file and can show a picture`?

> for a new instance, would it be possible to propose one day an option to either, embed the images in the database, or store images in an images sub-folder ?

I'm not sure about your phrase `an option to embed the images in the database`. They are already there by using command 'Insert Image'?

About storing images in an images sub-folder. On the one hand , it would be pretty simple to have images in files and show them from those files. On the other hand, this brings a lot of small issues:
- users are used to a single binary blob, now they should remember about an additional folder.
- how to make inner backups? because before, it is just a file copy.
- how to make UI to turn on/off the option with the image folder (it doesn't look simple at all)
- etc

I think, making full-functional image sub-folder is not worth it, but there are two ways to fix the issue:
- create a widget LinkToImage which behaves like a link to an image file and can show a picture. So, it is now a user problem to manage image files or how to sync them.
- don't use binary blob at all as an option. So notes are separate xml files, images/files are in dedicated folder. I see this option as an only solution for syncing big dbs. Maybe it has other advantages as well but it's too big step for now.

**Comment by ciranus** [comment]
> What do you mean by searching for images ? 

Unclear I admit.
In Nixnote2 (_linux clone of windows Everenote_), you can search notes containing images by date : not perfect, but it helps.
The easiest is even to directly browse the image folder with a file or image manager.

My worry with CT is always to insert images/snapshots, and 2 months later, I am sure I will not be able to find them.
The only possibility is to duplicate the image, both in CT, and in an image directory somewhere: then not optimal.

> It is unclear what you want. A link to a image file (without showing a picture) or an image in a note ?

Here is the current solution I had in mind with current CT, based on previous remark, and avoid image duplication:
- place CT images in a given image directory, and just drag the image from the file manager to CT, and automatically create a link to this image: `<path to>/image.png`.
Other possibility when dragging the image to CT: open a pop-up to propose 2 choices:
 1/ insert link to image ? ; 2/ insert image ?

> I'm not sure about your phrase an option to embed the images in the database. They are already there by using command 'Insert Image'?

Unclear if you forget "_or store images in an images sub-folder ?_"
Yes, images are currently in the database.
"_or store images in an images sub-folder ?_" would be for users who prefer having images stored in sub-folder (like nixnote2)

Or maybe, if finally having images stored outside the database is in the future considered as a preferred solution for all users, why not deciding to change image management for a future CT version, and only store images in a separate image folder.

Concerning your sync questions, nixnote2 is the linux version of windows Evernote client.
I've never used sync feature, but I have never seen images sync problem for Evernote/nixnote2 (then to be checked).

> users are used to a single binary blob, now they should remember about an additional folder.

I agree that this kind of modification is very late (too late) for 0.99, and making any decision would need time.
And I always had in mind that [gtk2 to 3] = [no feature modification].

Finally you said: 
> I agree with your point about the database size. That issue is especially acute for sync or backup when users want to have high-resolution images and scans (also, heavy embed files) in notes.

So let's consider this issue just as a brainstorm for the moment.
Needs more time to be sure any future modification will not break anything, and or creates any trouble.

(for further investigations, see  [nixnote2](https://packages.ubuntu.com/focal/nixnote2) )
