### ISSUE TITLE
Cant Adding a New Command for Code Execution 

### ISSUE THREAD

**Issue by Peterling007** [giuspen/cherrytree#1178]
(Using: cherrytree_0.99.12-1_amd64.deb in Linux Mint 20 Cinnamon - Live-System with persistence)

1. Probably Bug
go to Menu → Edit → Preferences → Section: Plain Text and Code
click the first Button with the “+-Sign” to start the Code-Language-Choose-Dialog
⇒ nothing happens, therefore it is not possible to add a new command for a supported language.

2. Annotation: 
The input field for the terminal command is very small; so reviewing / entering long terminal-commands is a little painful.

**Comment by funnelfiasco** [comment]
I can confirm the inability to add a new command described in 1 above. (cherrytree-future-0.99.11.20200918git370f605-1.fc32.x86_64 on Fedora 32 KDE)

The terminal command input field seems fine to me, though.

**Comment by giuspen** [comment]
Thanks I see it is missing in the porting I'm going to add shortly

**Comment by giuspen** [comment]
I added the part of code that was not ported yet from pygtk2, it works but I realise that it is lame that the user cannot edit also the extension of the temporary file generated from the preferences dialog (while can do it acting directly to the config.cfg). For example in my test I have added a custom command to the syntax of type "html" to be executed with firefox, it has worked but then the default extension is .txt so firefox was displaying the html as it was plain text.
I will add a column to the table so that the user will be able to specify also the extension of the temporary generated file, this will make this feature more usable.
