### ISSUE TITLE
Inserting today's node crashes application 

### ISSUE THREAD

**Issue by apondarz** [giuspen/cherrytree#1193]
Selecting "Insert Today's Node" makes the application crash.

Version: 0.99.13
Windows 10

**Comment by txe** [comment]
I cannot reproduce this issue. I also tried with a new document, still no crash.

The code is pretty simple, I don't know how it can be broken. Maybe it is related to Language\Region Settings in Win10 because cherrytree tries to make node names based on the system language. 

What language do you use in Win10? Also, can you remove/refresh the cherrytree config file?

**Comment by giuspen** [comment]
please try https://www.giuspen.com/software/cherrytree-test2.7z (extract and place cherrytree-test2.exe in the portable folder beside cherrytree.exe) then run it from a console and report what you see printed when it crashes

**Comment by apondarz** [comment]
You were right, it's because of language. Here is output from console:
```
(cherrytree-test2.exe:19072): Pango-WARNING **: 07:42:33.097: Invalid UTF-8 string passed to pango_layout_set_text()
[2020-09-30 07:42:33.102] [   ] [debug] Node name: wrzesie˝
```

September in polish is: wrzesień - it apeeaars that the last letter (n with acute accent) causes trouble.

Problem reproduced on two systems - one with  full polish language, one with english language but polish regional format settings.

**Comment by txe** [comment]
Thanks! I think I fixed it
I didn't try to use polish language, but I think I know what caused the issue to put the fix.
