### ISSUE TITLE
HTML import: colors partially lost

### ISSUE THREAD

**Issue by Hoffenbar** [giuspen/cherrytree#1217]
It seems that colors specified via style sheets are lost after import. In a browser the list elements from the following example are red, after importing in cherrytree, they are black. In contrast, the green and orange text is green and orange in cherrytree.

[coltest.zip](https://github.com/giuspen/cherrytree/files/5335412/coltest.zip)

**Comment by ciranus** [comment]
![2020-10-06_19-11](https://user-images.githubusercontent.com/61602511/95236906-d0742d00-0807-11eb-8dc2-2b25c357b567.png)
'red color' is not treated because defined as css header style, then not included in the clipboard.
```
<style>
   ul { color: red; }
</style>
```

**Comment by txe** [comment]
Yeah, @ciranus is kind of right. "color: red;" is placed in a header css style, and it's a lot of work to implement css specification. So we just parse html tags in an html file and that's all. 
I said the prev comment is kind of right, because if you copy/paste that html from any browser, html will have styles inside tags and we can parse it correctly.
