### ISSUE TITLE
Allow manual resizing of table columns

### ISSUE THREAD

**Issue by zauberparacelsus** [giuspen/cherrytree#123]
Would it be possible to add support for manually resizing table columns?  I sometimes find that the automatic column widths do not always turn out as desired, and it would be nice to be able to manually adjust them as desired.

**Comment by zauberparacelsus** [comment]
Bump?

**Comment by giuspen** [comment]
I'm sorry but have no time to take care of this for now

**Comment by qjensen** [comment]
I noticed that adding features to tables is on the wish list. That covers a lot of ground. The lack of this one feature is a bit of a pain for me. Not sure how much it affects others since this thread has been dormant for over a year. Is there there enough interest out there to fund this feature (assuming the author would even be interested)?

**Comment by giuspen** [comment]
There is no much room for improvement with the current pygtk2 implementation but in the new gtkmm3 implementation I'm using different widgets that support huge improvements. For now though the focus is in completing the porting.

**Comment by metal450** [comment]
Struggling a bit with this myself (in the gtkmm3 version).

It seems to auto-size such that all column widths are equal, which causes enormously wide tables in some cases. Example: I have 5 columns, 4 of which contain small single-word or numeric values, & one contains notes - but because of the notes column, all 5 end up super wide.  Or alternatively, if you set the max width so it looks bettr for the small values, the notes column ends up with the same max width, so instead, rows are super tall.  One way or the other, tons of extra space used.

**Comment by kleshas** [comment]
Another request for columns being different sizes.

**Comment by giuspen** [comment]
This is actually already done in 0.99.30
