### ISSUE TITLE
Exporting to PDF from XML broken

### ISSUE THREAD

**Issue by zixtor** [giuspen/cherrytree#124]
Create a new instance and make a node with following test content and save it as XML(not password protected):
"This is test writeup to export into PDF. This is test writeup to export into PDF. This is test writeup to export into PDF."

The exported pdf is attached:
[test.ctd.pdf](https://github.com/giuspen/cherrytree/files/224202/test.ctd.pdf)

CherryTree 0.35.2
Debian 8.3

Thank you for the nice software.

**Comment by giuspen** [comment]
Please install the latest 0.36.9 and check if you still have the problem
there
On 18 Apr 2016 17:26, "Atul Pratap Singh" <notifications@github.com> wrote:

Create a new instance and make a node with following test content and save
it as XML(not password protected):
"This is test writeup to export into PDF. This is test writeup to export
into PDF. This is test writeup to export into PDF."

The exported pdf is attached:
test.ctd.pdf
<https://github.com/giuspen/cherrytree/files/224202/test.ctd.pdf>

CherryTree 0.35.2
Debian 8.3

Thank you for the nice software.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/giuspen/cherrytree/issues/124>

**Comment by zixtor** [comment]
Ok, I just installed 0.36.9 but still see the problem.
