### ISSUE TITLE
python-gtksourceview2 deprecated, please port to PyGI

### ISSUE THREAD

**Issue by Vincent-C** [giuspen/cherrytree#125]
Forwarded from [Debian BTS #822586](https://bugs.debian.org/822586)

cherrytree depends on python-gtksourceview2, which is long deprecated and going to be removed from the archive. cherrytree should switch to using the GObject Introspection bindings for  gtksourceview, gir1.2-gtksource-3.0.

This would mean switching to GObject Introspection for other bindings as well, e.g. GLib and GTK+ 3.

For more information on GObject Introspection see [1] and [2].

[1] https://wiki.gnome.org/action/show/Projects/GObjectIntrospection
[2] https://wiki.gnome.org/action/show/Projects/PyGObject

**Comment by giuspen** [comment]
Thank you Vincent.
I plan to issue a major release 0.37 and after that I will start the porting.

**Comment by City-busz** [comment]
Is there any news? Version 0.38.0 is just released, but still uses gtk2 and the old python bindings.

**Comment by giuspen** [comment]
Yes, I will start the porting in few days, 0.38.x will be the last with gtk2

**Comment by giuspen** [comment]
Bad news unfortunately, as discussed in http://www.giuspen.com/topic/status-of-the-development/ I got stuck in the porting for the lack of binding of the function gtk_clipboard_set_with_data() which is essential in cherrytree. At the moment I'm evaluating the option to port to PyQt5.

**Comment by jbicha** [comment]
cherrytree was [removed](https://bugs.debian.org/822586) from [Debian](https://tracker.debian.org/pkg/cherrytree) Testing a couple months ago and will probably be [removed](https://launchpad.net/bugs/1731725) from Ubuntu before 18.04 LTS because python-gtksourceview is being removed from the repositories.

**Comment by giuspen** [comment]
I'm porting to gtkmm3 but it will take a while

**Comment by rhertzog** [comment]
Hello @giuspen what's the status of your port? cherrytree is a very much appreciated application in Kali Linux and we have kept it around despite the removal of python-gtksourceview2 hoping that you would complete the rewrite/transition at some point.

Also I wonder if time would not be better spent in actually getting the suggested patch merged upstream:
https://gitlab.gnome.org/GNOME/gtk/issues/364

Also in the mean time, would it not be possible to just make cherrytree work without python-gtksourceview2? If it's required only for a specific feature, then that feature could be disabled when the module is not available... but at least the package could be kept in Debian for longer.

**Comment by giuspen** [comment]
Hi @rhertzog the porting to gtkmm3 is proceeding slowly, you can see the commits in the subfolder "future". I still struggle to find time because of the kids.
I still think the best future for cherrytree is gtkmm and I will try and push a first complete but with less features version as soon as possible for then adding back all the features gradually.
GtkSourceView is paramount for the syntax highlighting in code nodes and code boxes, couldn't be that it was removed because integrated into newer python-gtk2 package?

**Comment by KitchM** [comment]
Hang in there, giuspen.  Your work is appreciated.

I  too found a problem with it not working on Debian.  Since I am moving to the latest, I am in a pickle.  (Like many others, no doubt.)  I could not find a way around getting it going on my system, so I must boot into an old OS to get to my database.

Please let me know if there is anything I can do with testing or whatever.

Say hi to the kids, and keep up the good work.  We appreciate it.

**Comment by giuspen** [comment]
Thanks @KitchM the porting is going ok especially thanks to the great contributions coming from @txe. The plan is to have the first release for the end of the year, we will probably make it. I will ask for help in testing when we will have an usable version, too early now for that. Take care 😉

**Comment by mayo83** [comment]
Hey, i also want to say that im thankfully that u are porting cherrytree. I use this tool now for a few months and i like it realy much. but today i started to convert my developing vm to debian 10 and was a bit frustrated to see that cherrytree isnt working. I also send u a few bucks via paypal. i know its not much but better then nothing. :)

**Comment by giuspen** [comment]
Thanks @mayo83

**Comment by goodleixiao** [comment]
Checking: gtk#364 (closed) it seems to be closed with the last comment of "The GtkClipboard api is gone."
Not sure how this affects this issue though.

https://gitlab.gnome.org/GNOME/gtk/issues/364

**Comment by KitchM** [comment]
Why did I receive this notification?

-- 
 Securely sent with Tutanota. Get your own encrypted, ad-free mailbox: 
 https://tutanota.com


Sep 26, 2019, 09:46 by notifications@github.com:

**Comment by hivemall** [comment]
It seems there is a snap to be released, @giuspen any news on
https://github.com/giuspen/cherrytree/pull/608 and any avail .snap - either snapstore or via https://github.com/giuspen/cherrytree/releases?

**Comment by hivemall** [comment]
Congratulations guys/gals
```
$ snap find cherrytree
Name        Version  Publisher   Notes  Summary
cherrytree  0.38.11  hellsworth  -      Hierarchical note taking application
```

**Comment by txe** [comment]
Closing, cherrytree was ported on Gtk3/C++

**Comment by KitchM** [comment]
Yea!  Well done Giuseppe and team!
