### ISSUE TITLE
CherryTree appears frozen

### ISSUE THREAD

**Issue by brownslink** [giuspen/cherrytree#1251]
# STEPS TO REPRODUCE
- Open tree node properties.
- Copy node name onto clip board.
- Task switch to another instance of Cherry Tree (leaving the first instance property pane open) to create a new node from the clipboard.
# OBSERVED BEHAVIOR
- CherryTree seems unresponsive.
# EXPECTED BEHAVIOR
- User can create a new node and paste the name from the clip board.
- Node property dialog is not modal across all instances of CherryTree.

**Comment by txe** [comment]
Hi, the other instance actually is not an instance, it is an additional window. Because that dialog is modal, it blocks any work with all windows/widgets as you noticed. I suppose you work on Linux, because for some reason linux DE allows to choose another window though it should be blocked in this case. On Win, it is blocked.
I checked available options to make the dialog less modal or somehow to unblock other windows, but no luck. I think this issue cannot be fixed.
