### ISSUE TITLE
Copy Paste Text with inserted text fields

### ISSUE THREAD

**Issue by Jaz-z** [giuspen/cherrytree#1314]
CherryTree 0.99.18
Operating System: Kubuntu 20.04 Desktop

Pasting text with inserted text fields, only pastes the simple text and not the inserted fields into cherryTree - so they have to be done one by one.
While copying the same text from cherryTree, then inserting in a libreoffice writer does paste everything.

**To Reproduce**
1- copy paste from the docx file attached into cherrytree
2- copy paste from the cherrytree file attached into a office writer document.

[Documents.zip](https://github.com/giuspen/cherrytree/files/5485199/Documents.zip)

**Comment by txe** [comment]
It cannot be fixed.

When text with text fields is copied into clipboard, the clipboard actually contains several formats of the given text: plain text, Rich text, HTML, Ole and others (easy to see by clipboard manager). And here Office Writer makes a trick: general formats (plain, rich, html) don't contain text fields at all, so we cannot retrieve this information (other editors cannot do it too). 

So why Office can paste text fields itself? Because there are other private formats in Clipboard which only Office can understand.  I'd like to suggest to convert text fields into something else, but I don't know how to do it.
