### ISSUE TITLE
0.36.100: Window can be lost when system tray icon clicked

### ISSUE THREAD

**Issue by piyo-gh** [giuspen/cherrytree#135]
Cherrytree 0.36.100
Windows 10 Pro x64

1. Switch on **Enable System Tray Docking** option.
1. Minimize cherrytree window.
1. Click on cherrytree's system tray icon. (This results hide cherrytree icon from taskbar.)
1. Click on cherrytree's system tray icon again.

**Result:**
Cherrytree icon on taskbar will be restored but cherrytree window is not restored.
And after that I cannot show cherrytree window manually at all, so I must exit cherrytree.

Current stable and 0.36.99 worked as following.

1. Switch on **Enable System Tray Docking** option.
1. Minimize cherrytree window.
1. Click on cherrytree's system tray icon.

**Result:**
 Cherrytree window will be restored from minimized.

**Comment by giuspen** [comment]
This is hopefully fixed in the current git version, please try the new
release that should come in few days
On 21 May 2016 07:34, "piyo-gh" <notifications@github.com> wrote:

Cherrytree 0.36.100
Windows 10 Pro x64

   1. Switch on *Enable System Tray Docking* option.
   2. Minimize cherrytree window.
   3. Click on cherrytree's system tray icon. (This results hide cherrytree
   icon from taskbar.)
   4. Click on cherrytree's system tray icon again.

*Result:*
Cherrytree icon on taskbar will be restored but cherrytree window is not
restored.
And after that I cannot show cherrytree window manually at all, so I must
exit cherrytree.

Current stable and 0.36.99 worked as following.

   1. Switch on *Enable System Tray Docking* option.
   2. Minimize cherrytree window.
   3. Click on cherrytree's system tray icon.

*Result:*
Cherrytree window will be restored from minimized.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/giuspen/cherrytree/issues/135>

**Comment by piyo-gh** [comment]
Thank you.
