### ISSUE TITLE
Menu element icons are not always visible

### ISSUE THREAD

**Issue by ValdikSS** [giuspen/cherrytree#1410]
**Version, Operative system**
Fedora 32, KDE Plasma 5.18.5, CherryTree 0.99.24 from Flatpak (commit `6d7ad2e0032cbe67f5ae4d6cd4b984fb0009e55b`)

**Describe the bug**
CherryTree menus sometimes do not show menu icons. This happens in different groups of dropdown menus, without any consistent pattern.

**To Reproduce**
1. Start CherryTree from Flatpak
2. Click on any top dropdown menu and hover over other menus to make them visible
3. One of the menus won't have either some menu items without icons or all of them

**Screenshots**
Check the video:

https://user-images.githubusercontent.com/3054729/123551079-e56b6480-d778-11eb-9f1b-03f03c53ffd6.mp4

**Comment by dardoor** [comment]
The same thing happens on Windows as well.

**Comment by giuspen** [comment]
I'm closing this because thanks to @userfav we have a new icon theme in 0.99.25 and some fixes upcoming in 0.99.26. Please wait for 0.99.26 and if you still have problems comment here or on a new issue

**Comment by userfav** [comment]
@giuspen I think that this problem is unrelated to the change of icons. It refers to when you open CT, sometimes the icons don't load when you open a menu (and appears to be random):

![imagen](https://user-images.githubusercontent.com/46328784/101897390-39ba4880-3b89-11eb-9089-bd6129fb8675.png)

until you hover the menu entry with the cursor (once they are loaded they stay visible) 

![imagen](https://user-images.githubusercontent.com/46328784/101897523-6ec69b00-3b89-11eb-8a9f-89b9fd49e5f8.png)

I see this happening on Windows and Linux (Cinnamon/KDE).

**Comment by giuspen** [comment]
I see thanks @userfav

**Comment by userfav** [comment]
Keep happening on 0.99.26 (tested on Windows 10 & Linux Mint Cinnamon)

**Comment by ValdikSS** [comment]
Can reproduce on 0.99.33 Windows and Linux Flatpak as well.

**Comment by ValdikSS** [comment]
The issue persists on Cherrytree 0.99.38 (Linux Flatpak).

**Comment by giuspen** [comment]
This should be fixed in upcoming 0.99.39. If you see it again please re-open the issue.

**Comment by ValdikSS** [comment]
Works fine, the issue is fixed, thanks.
