### ISSUE TITLE
Some Toolbar icons are invisible on dark theme @Linux

### ISSUE THREAD

**Issue by AliGeyik** [giuspen/cherrytree#1414]
[Screenshot](https://i.imgur.com/VutiM7a.png) 

$ apt list --installed | grep -i cherrytree
**cherrytree/groovy,now 0.99.25-2 amd64 [installed]**

**Comment by rogue-ronin** [comment]
It would be nice if we could customize the icons, as long as we're dreaming! :)

Cherrytree is the best!

**Comment by userfav** [comment]
@AliGeyik Yes... I guess it happens that your theme app background have the exact same color as the icons. Here I attach a fix to all the black icons (including the finders). I add a light border to them.

[icons_2020-12-10_update.zip](https://github.com/giuspen/cherrytree/files/5672580/icons_2020-12-10_update.zip)

**Comment by giuspen** [comment]
Thanks @userfav much appreciated

**Comment by T-2** [comment]
I have this exact problem. How do I add your fix to my cherrytree? I see they are just svg files but where do they go?

**Comment by giuspen** [comment]
the updated icons will be in 0.99.26

**Comment by userfav** [comment]
@giuspen I set up a virtual machine to test the looking of the icons with a dark theme, so I fix some of them that I dind't include in the first patch, simplify some of the smallest icons  and also gave them more contrast. Examples:

![imagen](https://user-images.githubusercontent.com/46328784/101937381-8d945400-3bc0-11eb-9461-e7731320aaf0.png)


Toolbar with llight/dark icons:

![imagen](https://user-images.githubusercontent.com/46328784/101936872-e2839a80-3bbf-11eb-9095-463348cfe6e9.png)
![imagen](https://user-images.githubusercontent.com/46328784/101936898-eb746c00-3bbf-11eb-81a6-3bb477c4c5a1.png)

Files: 

[icons_2020-12-11_update.zip](https://github.com/giuspen/cherrytree/files/5680773/icons_2020-12-11_update.zip)

**Comment by T-2** [comment]
Those work for me! Thanks

**Comment by giuspen** [comment]
Great job @userfav I'll update with your latest

**Comment by AliGeyik** [comment]
> @AliGeyik Yes... I guess it happens that your theme app background have the exact same color as the icons. Here I attach a fix to all the black icons (including the finders). I added a light border to them.
> 
> [icons_2020-12-10_update.zip](https://github.com/giuspen/cherrytree/files/5672580/icons_2020-12-10_update.zip)
> 
> @AliGeyik Forgot to ask, Is that Plasma DE?

Yes, v5.19.5

**Comment by userfav** [comment]
@aligeyik @T-2 Just asking for opinions of dark theme users here, in 0.99.26 you will see the icons, now for the 0.99.27, what you do thing about this mockup? (I'm specifically asking about the bold, strikeout, italic , underline, superscript/subscript, small and and monospace icons):

![imagen](https://user-images.githubusercontent.com/46328784/102269294-31e90400-3efb-11eb-846f-b9ad8bd1dc84.png)
![imagen](https://user-images.githubusercontent.com/46328784/102269332-3e6d5c80-3efb-11eb-9ab6-03e5ebf8b0c8.png)

This are the same icons on a light theme:

![imagen](https://user-images.githubusercontent.com/46328784/102269494-7aa0bd00-3efb-11eb-8cad-8e415fab68b0.png)
![imagen](https://user-images.githubusercontent.com/46328784/102269524-855b5200-3efb-11eb-8c2e-57c3507f00e5.png)

**Comment by T-2** [comment]
Even better! I like those!

**Comment by rogue-ronin** [comment]
I am a dark theme user, and I really like the white outline on the prior set. I'd like to see that around the red "h" in the header-size icons as well (in that set).

The black edges around the blue icons in this set looks blurry and indistinct to me. One of the points of a dark theme to me is for the icons to pop off the background with a burst of high-contrast.

I prefer symbolic icons, honestly -- the ones that use shaded colors are hard to decipher, especially when they're small. Too cartoonish -- icons are nearly becoming logograms now, and the clearer and simpler ones appeal to me because they don't require me to invest cognition in deciphering the artwork. I also like it when I can change the icon set to a different single, simple color.

Now that I know that you can change the icons by putting them into the configuration directory, I may just set my own up.

Thanks for all your hard work and the kindness of sharing it!

**Comment by userfav** [comment]
@rogue-ronin thanks for your feedback, I think that I will be going with something like this:

![imagen](https://user-images.githubusercontent.com/46328784/102298764-7cd13e80-3f30-11eb-9f5f-265e2a157d6e.png)
![imagen](https://user-images.githubusercontent.com/46328784/102298827-a25e4800-3f30-11eb-9950-675557474b33.png)


Still, some working is needed on them.

**Comment by rogue-ronin** [comment]
Looks nice!

**Comment by rogue-ronin** [comment]
Looking better every time!

Could I suggest that the bottom edges of the *x* the *arrow *in the top two
icons could use something to define them? Perhaps some white? You might
want to consider something similar with the indent and unindent blue
portions.

Also, you mentioned not wanting to use the first letters of bold, italic or
underline so that it would be more generic for other languages. You should
consider something for monospace as MS is clearly falling under this
rubric. Perhaps something that looked like an old-school LED letter A?
(Like on old red LED calculators or alarm clocks.) Or something slightly
more pixelated, like these letters:
https://www.dreamstime.com/dotted-text-electronic-digital-lighting-alphabet-letters-numbers-airplane-monitor-vector-set-display-scoreboard-dot-image171317519

Thank you for including me in this email chain, I really appreciate the
opportunity to give my observations and opinions.


Aloha!

**Comment by userfav** [comment]
@rogue-ronin Noted!, thanks for your feedback!

**Comment by T-2** [comment]
Excellent fix for the dark theme icons.
Thanks
