### ISSUE TITLE
Mobile-Friendly CherryTree for Ubuntu Touch, Mobian (Debian), Arch/Manjaro, et al.

### ISSUE THREAD

**Issue by DiagonalArg** [giuspen/cherrytree#1486]
Linux phones are just beginning to appear, with multiple options of OS, from Mobian (Debian) to Arch & Manjaro, along with the more phone specific UBPorts (was Ubuntu Touch), PostMarketOS, LuneOS, SailfishOS etc.

I am looking at [UBPorts](https://ubports.com/) now on my [PinePhone](https://www.pine64.org/), which has specifically been designed for linux, though UBPorts itself has been ported to a [number of Android phones](https://devices.ubuntu-touch.io/).  It has a means of running [containerized desktop applications](http://docs.ubports.com/en/latest/userguide/dailyuse/libertine.html),  though of course Mobian, Arch and Manjaro run them natively.  Perhaps you folks would like to consider a mobile-friendly version of Cherry-Tree for these rapidly developing platforms?

I hope so!  :)

**Comment by petrisch** [comment]
This is similar to this: #1024  

It can be used already since the gtkmm3 version.
I use it as a flatpak on mobian, but the native version works as well i guess.  

It will be a ton of work of course to bring it on gtkmm4 and use something like libhandy.
Also it would require lots of UI design ideas for not diminishing the desktop experience.  

For me, on mobile I mainly want to *read* my notes. And I can already do that.

**Comment by DiagonalArg** [comment]
Excellent, @petrisch , thanks for your blog post!  :)

I would like to differ with you though, regarding use.  I take notes on my phone all the time.  I don't need a lot of markup, it's true. 
 Indeed Markdown would do fine.

Closing as covered by your previous issue.
