### ISSUE TITLE
0.99.34 New Logging In Config Dir

### ISSUE THREAD

**Issue by metal450** [giuspen/cherrytree#1614]
Hi; I just updated to 0.99.34 & found a new log file being written to the config directory. Could I request a way to disable this, or alternatively, to log to a different location?  I have my config folder as part of my sync & backup tasks, & this introduces an extra file that gets repeatedly uploaded, but doesn't really need to be (i.e. I don't need the logs synchronized between all my machines, I like my config to be).  Thanks!

**Comment by metal450** [comment]
Related: there also seems to be a new duplicate config file, .cfg.tmp. My guess is that this may be a backup.  Would be cool if this similarly went to the dir configured in Misc->Custom Backup Directory, or similar - for the same reason.  My core CherryTree data (database & config files) are synced & backed up; the 'redundancy data' (aka CherryTree's own backups) are in a separate location - kept on each local system for safety, but not synced or pushed to my remote backups.  Thus, it's preferable to keep the 'core data' as clean as possible, to minimize excess syncing/uploading, where possible.

Thanks!

**Comment by giuspen** [comment]
I will add the possibility to disable it and maybe to log elsewhere

**Comment by giuspen** [comment]
About the config.cfg.tmp it is actually a newer version on the config.cfg that is then moved to config.cfg as cherrytree starts. It is a trick to allow writing the config down at operative system shutdown as quick as possible (that path is empty because cleared by cherrytree at start). I have not thought about anybody synching the config folder, I still need to use a subfolder there... isn't it possible for you to filter out filenames from the synchronization?

**Comment by metal450** [comment]
Filtering is possible, but IMO it's a lot cleaner to have 'temporary' (work) files in one place, separate from the permanent config.  Aside from making the configuration of sync & backup software a lot more confusing & case-specific, it requires exceptions in the sync software x3 client PCs, plus backup software x3 client PCs.

Alternatively, perhaps just the option to turn this off - aka go back to the old behavior? Which would mean no protection against loss of config if you reboot your PC without quitting CherryTree, with the tradeoff of the tidier config dir :)

**Comment by giuspen** [comment]
I will surely put something in the config.cfg just not sure if will spend time for the UI for it, so you may have to edit manually the config file

**Comment by metal450** [comment]
in the config file is 100% no prob :)

**Comment by ciranus** [comment]
My 2 cents.

**1** - log file
I also consider log file should not be enabled by default (unless 0.99.36 is considered as a development release).
There are already some debug options:

CT  GTK+ options
--g-fatal-warnings
--gtk-debug=
--gtk-no-debug=

Instead of any UI modification to enable/disable log, why not simply adding a '--log' on/off option (the log is only necessary to investigate when needed, for development).

**2** - config.cfg  + config.cfg.tmp
Not convinced it is really useful, and a bit confusing: which one should be manually edited (it happens to me to directly edit the config file).
How many threads since CT creation have exposed that missing a bit of configuration caused by an **unclean** close operation was a real issue ?
Loosing data is not the same priority level than loosing one bit of configuration.
This is Just a comment, a feeling, nothing more.

**Comment by giuspen** [comment]
The .tmp issue has been already taken care, you are going to see it only if you reboot with cherrytree running or kill cherrytree. About the log I'll do something shortly, I thought would be no harm to have the log always on to capture something the user may not easily reproduce but I may disable it by default anyway, certainly configurable

**Comment by giuspen** [comment]
Ok the log enable/disable + location will be configurable in 0.99.37
