### ISSUE TITLE
Ty for crash, i'm just crying after 1 hours of write STUFF on CHERRY TREE... me fine :((

### ISSUE THREAD

**Issue by Yaronmiku** [giuspen/cherrytree#1756]
Ty for crash, i'm just crying after 1 hours of write STUFF on CHERRY TREE... me fine :((

**Comment by mm47** [comment]
Have you taken some time to configure CherryTree? There's an option to "autosave every [amount defined by you] minutes", another option for "autosave on quit" and, one of the most important options "create a backup copy before saving". And, right below it there's another option "number of backups to keep [amount defined by you]". I set up my autosave for 5 minutes and the backup copies to be kept to 50. 
When testing a new software, it's crucial to configure it in a way that, no matter what happens, we won't lose too much.
What version of CherryTree and operating system are you using?

**Comment by Yaronmiku** [comment]
yes i used automatic saving, but it's still lost a lot of data when it's crash ;-;
also when my cherryfile it's reach 300mb with 1 backup DATA, it's take up so much time to wait zzzz
**NEWEST version of CherryTree, WIN 10 Home

**Comment by Yaronmiku** [comment]
![image](https://user-images.githubusercontent.com/60863634/126061283-58f7f955-3a7c-477e-8b97-206bf28bac93.png)

**Comment by Yaronmiku** [comment]
![image](https://user-images.githubusercontent.com/60863634/126061396-463b0694-8711-43bb-a1ea-fdd64ab933f4.png)

**Comment by Yaronmiku** [comment]
1 back up+ 1 orginial file = near 1Gb.....

**Comment by Yaronmiku** [comment]
1Gb write to disk is very long you know....also it make Hard drive life is reduced LIFE SPAN quickly because of using cherry tree too much

**Comment by Yaronmiku** [comment]
Any other take note program better than this cherry tree ???? i like this cherrytree it's best software i ever tried ;-; but too much 
PLOT-TRICK BUG
***May be later, i will program my-self a better TAKE-NOTE program..... this program it's just reach 6/10 and it's best program i ever know ;-; 
REALLY have no idea how to fix bug ;-; if im use my-self MY OWN TAKE NOTE alone ;-;

**Comment by mm47** [comment]
I don't use Windows, so I can't tell you exactly where the files are. Two things:
1- Have you saved in SQLite or XML? Is it protected?
When working on a password-protected file, CherryTree shows a warning saying that the database is unencrypted and stored on a temporary folder when open and deletes it once the database is closed. But if there's a crash, the file remains unencrypted in the temporary folder. I suggest you look for temporary folders on your Windows. AppData and any other hidden system folders. If you are lucky, it may still be there.
![Captura de tela_2021-07-18_19-43-04](https://user-images.githubusercontent.com/28028426/126084524-0066750f-87e5-405c-bff0-faf16c161b58.png)


2- Regarding the long time to save, if you chose to save as XML, CherryTree takes a long time because it has to rewrite the database everytime a change is made. Saving as SQLite doesn't take too much because the changes are just ADDED to the database, so there's no rewriting of it, therefore, it saves faster. That said, you could comfortably change the autosave to every 5 minutes if working with a SQLite database.

**Comment by mm47** [comment]
If you think CherryTree is not for you, you could try **[Zim](https://www.zim-wiki.org/)**. It has a similar approach.

**Comment by Yaronmiku** [comment]
i use SQLite, it's same.... still rewrite stuff and take up so long

**Comment by Yaronmiku** [comment]
%appdata% it not have any  temporary folders 
![image](https://user-images.githubusercontent.com/60863634/126140045-6c65b933-af12-4ec7-ac34-f63eec4799bd.png)

**Comment by mm47** [comment]
SQLite doesn't rewrite what is not being used. I'm using it and saves super fast. Here, an excerpt from the CherryTree manual:

> "SQLite is a self-contained database and has a .ctb or .ctx extension when used with Cherrytree. Instead of loading the complete document at runtime, Cherrytree only accesses the tree structure and selected node. This makes opening your document faster but may slow functions such as searching and selecting nodes when they’re used for the first time in a session. **Only modified nodes are rewritten upon saving, decreasing save time**.

> Performance loss with SQLite is lower than with XML, making it better suited for larger documents. The Save and Vacuum feature should be used periodically to keep SQLite files compact.

And here about the XML:
> XML is a markup language and has a .ctd or .ctz extension when used with Cherrytree. These files are fully loaded at runtime, making searching and navigating through nodes faster, but slowing the initial load time. **They are also completely rewritten upon saving, slowing the save process**.

> XML is more accessible and easier to convert to other file types but should not be used with large documents."

I would suggest there's something wrong with your operating system or machine. I'm sorry, but you lost your work. All softwares will crash at some point and make you lose your work, that's why we have to save **constantly**. 

You have some alternatives:
1- Try another software (Zim, Evernote, OneNote, Google Docs);
2- Write your own software like you said you would;
3- Move on and save every 5 minutes to not lose too much next time.

**Comment by Yaronmiku** [comment]
ty for information BTW OwO
