### ISSUE TITLE
Feature request - make code box dynamic

### ISSUE THREAD

**Issue by RichardJECooke** [giuspen/cherrytree#197]
Please have a codebox property (the default probably) to make a codebox fit to the height of the contained text.

Like this:

``` sh
the box is as long as the text below, like most markdown/creole/restruturedtext works

a long 
script
that 
does things
rm -rf /
git rebase -i
sudo reboot now
```

PS. Just started using CherryTree after getting sick of Evernote. Such a great app! Thanks.

**Comment by joseluis** [comment]
Related: #141

**Comment by philippHRO** [comment]
I would not suggest making this the default behavior. When you have lots of text in codeboxes, that you ALSO want to display completely, why not create a dedicated node for that?

The more common usecase for codeboxes (IMHO) is to have code snippets somewhere in a rich text node. And here it would be frustrating to have the codebox automatically resize to it's content. More often than not, I need the codebox to stay the height which I entered.

**Comment by phd21** [comment]
I too would like to see options for dynamic code box or user defined code box. If you are putting in a single console terminal command, it would be nice to have it automatically shrink to that size, at least vertically.

**Comment by 2SI3NX** [comment]
Agreed, a dynamic codebox would be much more useful rather than entering guessed sizes each time after selecting a piece of text.
Please make this feature possible! thank you much

**Comment by Techika** [comment]
**+1 from me to the request.**
I tend to save a lot of small codesamples in my KnowledgeBase section.
If its up to about 10 lines of code it would be great to be able to have the bracket auto-adjust to it instead of having to use (Alt+)Ctrl+, to finetune the height. 

**More personal comments:**
I also switched partially to Cherry from Evernote yesterday. 
(now using One+Cherry+Ever for distinct scenraios, to compensate their shortcomings and utilize their strengths)

**The perfect app would be:**
OneNote framework with Tags similar to Ever + Tabs&CodeHandling similar to Cherry + VBA support

**Comment by Betalord** [comment]
I believe this is an important feature. Is someone actually working on implementing it?
Also, syntax highlighting should be added outside of a codebox too (I would like to select for example a single line of text and enable highlighting for that, like inline code, and not block code).

**Comment by hb20007** [comment]
I believe this can be closed now.
