### ISSUE TITLE
CVE-2022-35133 reported against old version?

### ISSUE THREAD

**Issue by codehelp** [giuspen/cherrytree#2099]
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-35133

It's not clear if this CVE is known to upstream, already fixed or not yet reported to upstream. The CVE claims the problem exists in 0.99.30 which is an old release from 24 Jan 2021.

If there are problems viewing the video linked from the CVE, the process involves creating a new subnode with a name which embeds HTML and then deleting the node which triggers the embedded HTML.

**Comment by malcolmlewis** [comment]
Hi
I'm the openSUSE Cherrytree maintainer and it's reported to exist against versions 0.38.2 (SLE 15 SP3/openSUSE Leap 15.3), version 0.99.42 (SLE 15 SP4/openSUSE Leasp 15.4) and version 0.99.48 (openSUSE Tumbleweed).

Bug Reference: https://bugzilla.suse.com/show_bug.cgi?id=1202513

**Comment by giuspen** [comment]
I've been told that the bug is fixed now so I'm closing this, reopen with details on how to reproduce if it is not

**Comment by malcolmlewis** [comment]
Hi, I'm assuming it doesn't affect 0.38.2, likewise for 0.99.42 and up?

**Comment by giuspen** [comment]
I have't time now to track down when exactly the issue was fixed but I believe in
0.99.45 fixed issue with tags in dialog messages introduced in 0.99.44 (#1890, #1897)
after partially fixing . causing regression in
0.99.44 fix info dialog indicating pattern not found when pattern contains ampersand (#1876)
