### ISSUE TITLE
[Resolved]: setting monospace character changes background color

### ISSUE THREAD

**Issue by ynoxia** [giuspen/cherrytree#212]
Hi Giuspen,

I have this behaviour in my CT installation, and I would understand if it is a CT bug, or it is depending to my Fedora Linux environment.

I use CT in Cobalt style scheme. When I set some text to render in monospace style, background color of text becomes gray, only for characters ( not entire line ). The rest of line remains the dark background color of Cobalt style.

Please, can you check this behaviour? Is it related to my environment, or is a bug of CT ?

Thank you.

**Comment by giuspen** [comment]
Hello Giulio.
This is not a bug, it's been me a bit cheeky and rushed to push this in a
0.37.x version with configurability only editing manually the config.cfg
This is configurable graphically in the upcoming 0.38.0 but for now if you
don't like the monospace background you have to edit with a text editor the
config.cfg that you can find clicking the top menu help--open preferences
folder.
The key to edit is monospace_bg=, if you delete all up to = you disable it
otherwise you change color.


On 5 Dec 2016 14:21, "Giulio A." <notifications@github.com> wrote:

Hi Giuspen,

I have this behaviour in my CT installation, and I would understand if it
is a CT bug, or it is depending to my Fedora Linux environment.

I use CT in Cobalt style scheme. When I set some text to render in
monospace style, background color of text becomes gray, only for characters
( not entire line ). The rest of line remains the dark background color of
Cobalt style.

Please, can you check this behaviour? Is it related to my environment, or
is a bug of CT ?

Thank you.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/giuspen/cherrytree/issues/212>, or mute the thread

**Comment by ynoxia** [comment]
OK. 👍 

Resolved editing config.cfg as you suggested.

Thank you for your support.
