### ISSUE TITLE
Unable to paste pictures(copied from browser) to cherrytree

### ISSUE THREAD

**Issue by MasonJia** [giuspen/cherrytree#2156]
Version: 0.99.48
OS: Win10.

**Describe the bug**
the issue is simple, it is exactlly the same with issue #1203. I reviewed that issue description, it is exactely the same.
I noticed for bug #1203, the root cause was "a folder was missing in the distributed portable and installer causing the download of images from the internet to fail, should be ok in upcoming 0.99.16".
so i checked the latest version (0.99.51) source code, and find that in scripts/msys2_prepare_standalone.sh, the line "rm -rf ${NEW_MINGW64_FOLDER}/ssl" still exist, so I assume this issue also exists on the latest version.
I checked also the changelog.txt, it's not showing any feature request/bug update on ssl.
so is it possible to enable "pasting images from browser to cherrytree" feature in next iteration?

Thanks in advance.

:)
Jia Mason

**Comment by datavectors** [comment]
In Ubuntu desktop I can use Flameshot to capture/save browser images.
If I capture image to Clipboard I can switch to CherryTree instance/node and paste the image. Is this an acceptable workaround?

**Comment by MasonJia** [comment]
> 

Hello.

Thanks for your reply!
Yes I also noticed that I'm able to copy/paste images from the Snipshot , and I can also insert images one by one in Edit > Insert image. But sometimes I need to copy a whole page from browser, with a mixture of text/images, and in this situation, I can only paste the text part, but NO image. 
I agree that snipshot can be a workaround, but not a 'solution'.
The thing is, this issue was solved once so I assume it's not very difficult to fix it again, right? That's only my assumption.
Again, thanks for your reply
:)

Mason

**Comment by MasonJia** [comment]
closed this by mistake, reopening it.

**Comment by giuspen** [comment]
The problem that you are describing seems to be different.
I assume that if you right click on a single image on the web browser and select copy image, then paste into cherrytree it works, right?
If you select instead a section of a web page, copy and paste into cherrytree, that before trying to download the images is parsing the html code behind and only after that tried to identify the images.
In this case the parsing is in constant improvement and can fail. If you give me an example of web page, web browser and selection that fails I can try to reproduce the issue.

**Comment by datavectors** [comment]
In such scenarios I tend to look for alternative approaches in the interim rather than expecting bug fixes or new features from developer. Improvise.

For example for some workflows I now use CherryTree document as a "container (leveraging the tree hierarchy) and then reconstructing nodes into a new structure. As one example I recently realised that CherryTree can be used to create Reveal.js slideshows, when each node is a slide or fragment. The final HTML content is edited to include Reveal.js content. And the same approach applies in creating Markdown from CherryTree source nodes.

In your example I would assign one node as the "parent node" for each target web site. Then create a child node for each fragment (image or text) in time sequence. 

Then you can export that single parent node, with child nodes, into PDF or HTML and use this as a concatenation of images and text.

Another tip is to use Python with BeautifulSoup to reconstruct.

Remember that CherryTree is an XML format and the contents of any CherryTree node (with child nodes) can be parsed and reconstructed.

In fact the Python can be also written into a CherryTree code box. 

I have not found this "container" approach discussed anywhere but it offers new workflows using CherryTree. I am currently creating Reveal.js slideshows and Markdown using this approach. So your images and text could be slides and fragments in a Reveal.js show. CherryTree is being used in node time sequence in this example.

It is a new approach I am following where the tree structure can be used as time sequence, stepping through nodes from the top.

In using this approach it is helpful to use automation scripting, depending on whether you are in Ubuntu, Windows. I am in Ubuntu but the principles apply cross platform. Python can be used for such automation workflows.

**Comment by MasonJia** [comment]
> The problem that you are describing seems to be different. I assume that if you right click on a single image on the web browser and select copy image, then paste into cherrytree it works, right? If you select instead a section of a web page, copy and paste into cherrytree, that before trying to download the images is parsing the html code behind and only after that tries to identify the images in it. In this case the parsing is in constant improvement and can fail. If you give me an example of web page, web browser and selection that fails I can try to reproduce the issue.

Hi Giuspen,

WOW, big brother replied me!

I tried again to reproduce that issue, and found something different.
For the website I always visit, is a tech web called 'wowotech' http://www.wowotech.net/device_model/421.html, every image on its website is in '.gif' format(didnt notice this before, because those pictures have no 'motions'). Still, I can NOT copy then paste it into cherrytree.
Then I visited some other news website, and found that pictures in '.jpg' format can be pasted in cherrytree.
As ‘.gif’ pictures is not common in website, so I intend to callback this 'issue'.
Sorry for this false alarm.

**Comment by MasonJia** [comment]
> In such scenarios I tend to look for alternative approaches in the interim rather than expecting bug fixes or new features from developer. Improvise.
> 
> For example for some workflows I now use CherryTree document as a "container" (leveraging the node hierarchy) and then reconstructing nodes into a new structure. As one example I recently realised that CherryTree can be used to create Reveal.js slideshows, where each node is a slide or fragment. The final HTML content is edited to include Reveal.js scripts and content. And the same approach applies in creating Markdown from CherryTree source nodes.
> 
> In your example I would assign one node as the "parent node" _for each target web site_. Then create a child node for each fragment (image or text) in time sequence.
> 
> Then you can export that single parent node, with child nodes, into PDF or HTML and use this as a new concatenation of images and text.
> 
> Another tip is to use Python with BeautifulSoup to reconstruct.
> 
> Remember that CherryTree is an XML format and the contents of any CherryTree node (with child nodes) can be parsed and reconstructed.
> 
> In fact the Python can be also written into a CherryTree code box.
> 
> I have not found this "container" approach discussed anywhere but it offers new workflows using CherryTree. I am currently creating Reveal.js slideshows and Markdown using this approach. So your images and text could be slides and fragments in a Reveal.js show. CherryTree is being used in node time sequence in this example.
> 
> It is a new approach I am following where the tree structure can be used as time sequence, stepping through nodes from the top.
> 
> In using this approach it is helpful to use automation scripting, depending on whether you are in Ubuntu, Windows. I am in Ubuntu but the principles apply cross platform. Python can be used for such automation workflows.

Hi datavectors,

Thanks for your reply again.

I have replied Giuspen in previous comment, that I would like to call-off this issue because I found that the images that can NOT pasted into cherrytree is in '.gif' format and that format is not so common.
:)

Mason
