### ISSUE TITLE
Too big, too many files

### ISSUE THREAD

**Issue by ags1234** [giuspen/cherrytree#2212]
Just tested cherrytree_0.99.54.0_win64_portable.

The program is nice, but really, I cannot get over the fact that it's 435 MB and it has 17.130 files and 1.406 folders. Just for a hierarchical note taking application?

It's not that I don't have that space. Has the concept of efficiency completely disappeared?

**Comment by giuspen** [comment]
One big factor in the size is the support for LaTex rendering. This is doubling the size of cherrytree or more if I remember correctly (I'll have to check again) and could actually be removed with only the so called LatexBoxes not being able to render the maths formulas (but you would still see the LaTex source code, you would not lose data).
In fact I had a thought about releaseing also a no-Latex package bundle, I'm curious if many users would find that useful?

Another factor is that the excellent and totally free GTK3 libraries in use are native Linux, not native Windows, and in order to run on Windows need to carry over a small Linux distribution.

**Comment by teherauto** [comment]
Yeah, same problem... :-)
The app is magnificent, but the size and a lot files is terrible. 
Maybe you could make LaTex a separate downloadable add-on?

**Comment by gntech** [comment]
I would like a no-latex windows package

**Comment by giuspen** [comment]
I added the nolatex versions under https://github.com/giuspen/cherrytree/releases/tag/0.99.54
