### ISSUE TITLE
Bi-state checkboxes

### ISSUE THREAD

**Issue by Kansai53** [giuspen/cherrytree#2551]
In ToDo lists, checkboxes are tri-state. Since there's no way to bulk-uncheck ([this issue](https://github.com/giuspen/cherrytree/issues/1863)), manually unchecking them needs you to check all of them twice. As a way to mitigate this work, it would be nice if they could be bi-state instead of tri-state, so you only need to manually click all of them once to reset. I tried specifying only two characters in Preferences->Special Characters->Chars for Todo list, but it wouldnt let me.

**Comment by gitvectors** [comment]
I responded to your earlier discussion. I have no links to the creator of CherryTree, giuspen. I'm Just a fan and keen user of CherryTree. It helps to know what OS you are using since different ideas emerge. I dual boot Windows/Ubuntu.

**Comment by gitvectors** [comment]
Great. Then start with Ubuntu as example.  Read the original post where I posted different workflows. Install XNLCopyEditor si that you can browse XML content to view your checkbozes, Capture the absolute path to your ^.ctd as a Python variable to use. Learn xquery in XMLCopyEditor. and or learn xml.etree. and learn how to use CodeBox with Python script.  Then you are ready to go. When I have time I will experiment further.

**Comment by Kansai53** [comment]
Responded in the other thread. It's an interesting idea, but honestly not really able to implement a separate Python script at this time.

**Comment by gitvectors** [comment]
Then just parse the *.ctd as raw text using any other text substitution tool. the XML route is really for all options such as parsing node content but your need is simpler.

**Comment by Kansai53** [comment]
Sure. Would still be good (& presumably simple) to just allow checkboxes to be bi-state rather than tri-state.

**Comment by gitvectors** [comment]
It's the straw on the camel's back.
 I thought up another idea. There is a UI emulation tool Actiona (cross platform) which automates actions such as finding TODO checkboxes (as one example) then applying commands. It is quite usefull to automate any number of app GUI's since it emulates you clicking on TODO boxes. I started today by grabbing screenshots of the tick boxes to search forfor but other priority tasks took over.

Here are the target images.

![target1](https://github.com/user-attachments/assets/db65a0ac-129a-455f-8824-68e89b47d76f)

The Find Image widget in Actiona can loop through your TODO. when found run a procedureW

![target2](https://github.com/user-attachments/assets/ce1191bc-68b7-4443-8304-79db386cdd1d)

![target3](https://github.com/user-attachments/assets/d6296edd-4976-401d-a3eb-62f4a671b722)

Yet another idea is to keep a clone of your TODO list in one node then substitute one node for another to untick all. But if they are scattered far and wide then Actiona can automate the process. Sublime Text editor is another tool to parse XML.

**Comment by Kansai53** [comment]
Actiona: Oh now THATS a cool solution! Definitely handy, great to know about - thanks!

**Comment by gitvectors** [comment]
Footnote:

I too have > 50 "TODOS" to action.

I have decided that the CherryTree built in lists feature is too basic for my needs. So I will pivot and use Actiona as the primary Task Manager, calling through commands the appropriate *ctd document(s) or internal node(s) for each task. This is a more flexible workflow. The entire lists of tasks is written in ActionScript file in Sublime Text then imported (instead of using the Actiona editor which auses tiny fonts).

In fact this Actiona script (*.ascr) be embedded in CherryTree as CodeBox. Then run using actexec command.

**Comment by gitvectors** [comment]
If anyone is reading this I have devised an even closer binding of CherryTree and Actiona, not needing an external edittor such as Sublime Text. The usage pattern goes far beyond  just TODOS management.

**Comment by Kansai53** [comment]
Wow, OK that works. 
* I'd tried 🔲✅, which it wouldn't allow; 
* I also tried 🔲🔲✅, which does not work. 
* But 🔲✅🔲 works. So evidently you must put the "different" character in the middle of the "same" characters. A bit unclear, but great to have a solution!
