### ISSUE TITLE
Build-depending on a unmantained, outdated library

### ISSUE THREAD

**Issue by winnieXY** [giuspen/cherrytree#2562]
Hey,

I got (as Debian Maintainer of cherrytree) a bugreport that the cherrytree package within debian build-depends on a outdated and unmaintained library - which is still using gtk3 instead of gtk4 or 5.

See the original bug report here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1079436

For a hint how to cope with that situation have a look here: 
https://gnome.pages.gitlab.gnome.org/gtksourceview/gtksourceview5/porting-guide-3-to-4.html

**Comment by winnieXY** [comment]
In addition to that you depend on libgtksourceviewmm, which seems to be a dead upstream:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1079433

The last commit is 4 years ago:
https://gitlab.gnome.org/GNOME/gtksourceviewmm

and there was/is never a stable gtk4 branch  - just a wip branch here:
https://gitlab.gnome.org/GNOME/gtksourceviewmm/-/tree/gtksourceviewmm-4?ref_type=heads

But this is already 5 years old.

**Comment by giuspen** [comment]
Hi @winnieXY thanks for reporting, I understand the problem.
Ideally I should try and work on libgtksourceviewmm4 myself to point to libgtksourceview4 as that is still based on gtk3 and it shouldn't take too long.
Another option would be to access gtksourceview4 directly with the C API / no C++ binding and drop libgtksourceviewmm
I'm planning in future to port cherrytree to gtk4 / gtkmm4 but I don't want to rush that because older linux distributions don't support gtk4 yet.
I will investigate and update here.

**Comment by giuspen** [comment]
The porting to libgtksourceview-4 is complete and will be in the next release v1.2.0
