### ISSUE TITLE
g++: error: ./libp7za.a No such file or directory

### ISSUE THREAD

**Issue by luisniebla** [giuspen/cherrytree#418]
Hey I got curious about future/ and tried build it. You have install instructions so I don't know if we have to wait for the 1.0 version before we can use it. Anyway I get the above error when trying to make the directory :), wasn't sure if I did something wrong on my end.

**Comment by giuspen** [comment]
The /future is not usable yet, at the moment it is reading all 4 cherrytree document types and only partly visualising the content. You should be able to build it though with ./autogen.sh && make (tested only on Ubuntu 16.04 and 18.04 so far). 
If you send the whole log I can have a look.

**Comment by txe** [comment]
I encountered the same issue. Supposedly, `./configure` doesn't see `libp7za.a` as cherrytree dependence and as a result of it `make` doesn't build it. Adding `libp7za.a` to LDADD variables in `/future/Makefile.am` fixes it for me:
```
cherrytree_LDADD = ${CHERRYTREE_LIBS} libp7za.a

run_tests_LDADD = ${CHERRYTREE_LIBS} libp7za.a
```

BTW, @giuspen  do you need some help with this project? I'm quite good at C++ and could do small things for the project if you would like.

**Comment by giuspen** [comment]
Thanks @txe for providing a solution, I'm curious about what os you're building it in since it has built fine on Ubuntu 16.04 and  18.04. About the offer to implement some parts, that's surely appreciated, all the features of the python app are to be ported, so you can start to look at the code and propose something yourself or wait for me to prepare the ground for something to be completed from you

**Comment by txe** [comment]
Good, then I'll take a look at what I can do. Speaking of os, I use Manjaro (Arch).
