### ISSUE TITLE
International characters 'apostrophe' and 'quotation mark' not behaving as expected when using United States-International keyboard layout (Windows 7)

### ISSUE THREAD

**Issue by fmdiaz** [giuspen/cherrytree#427]
United States-International keyboard layout assigns special functions to a few keys (that is actually the main reason for using this layout, as it allow to write different languages without switching layouts).
From [https://support.microsoft.com/en-au/help/306560/how-to-use-the-united-states-international-keyboard-layout-in-windows](https://support.microsoft.com/en-au/help/306560/how-to-use-the-united-states-international-keyboard-layout-in-windows):

> When you press the APOSTROPHE ( ' ) key, QUOTATION MARK ( " ) key, ACCENT GRAVE ( ` ) key, TILDE ( ~ ) key, or ACCENT CIRCUMFLEX,. also called the CARET key, ( ^ ) key, nothing is displayed on the screen until you press a second key:
>- If you press one of the letters designated as eligible to receive an accent mark, the accented version of the letter appears.
>- If you press the key of a character that is not eligible to receive an accent mark, two separate characters appear.
>- If you press the space bar, the symbol (apostrophe, quotation mark, accent grave, tilde, accent circumflex or caret) is displayed by itself.

In cherrytree, both apostrophe and quotation marks keys ignore part of the functions and behave like if they were the special case symbol --i.e, the APOSTROPHE ( ' ) key always displays an accent ( ´ ) after pressing a second key, this behavior is the expected with the eligible keys, but when pressing another character or the space bar you expect an apostrophe.

This makes impossible to write apostrophe and quotation marks without switching keyboard layout. Though not a big issue from the user side, it is really odd as I never had this issue with any other software. And it could be considered an accessibility issue taking into account multilingual users who expect to write these characters as they are used to.

**Comment by Chaplin-Sec** [comment]
Yeah I can confirm, I will be rolling back to the old version in tn the mean while.

I can't type code into my databse anymore as it changes the apostrophe as mentioned above.

This is also affecting linux version as well.

**Comment by txe** [comment]
The issue is mostly related to Gtk2, not exactly to cherrytree.

About linux, it should work from the box. I just checked on Ubuntu and it worked fine. If it didn't work then it didn't work for other gtk2 programs (inkscape, gimp), gtk3 and Qt is a different story. So, if it doesn't work on Linux, you have to ask about it on some specialized sites.

About windows, I checked other gtk2 program on windows (like inkscape and gimp) and they handle it. I pretty sure that the problem is with gtk2 binaries that go with cherrytree because 'gtk-demo.exe' has the same issue. Unfortunately, bold replacing gtk2 binaries from those programs into a cherrytree directory didn't work (cherrytree just didn't start), but I have a feeling it's a right direction. I will try other gtk2 builds until the issue will be gone.
