### ISSUE TITLE
HTML output

### ISSUE THREAD

**Issue by CGizmos** [giuspen/cherrytree#668]
I'm going to have to revert to a previous version. 

Links tree in every page is ignored - the tree is only there for index and no page gets shown with index. If I link to a specific html page, the index disappears.

Styles2.css seems to be ignored. I try to change h1 color/style and there is no effect.

The expanding index is a nice little effect, but not if it really breaks things.

**Comment by txe** [comment]
I'll take a look how to fix it.

**Comment by txe** [comment]
Hi,
I've made some fixes which, I hope, will help you.
You can either wait for the next release (probably, the next weekend), or update files manually if you used a standard installer (not a snap). The latter is better because in case of any issue I will fix it on-the-fly.
Files to update:
- `usr/share/cherrytree/modules/exports.py`
- `usr/share/cherrytree/glade/style2.css`
- `usr/share/cherrytree/glade/script.js`
New files you can take from the github (modules and glade folders).

In both cases you will need to remove 'style2.css' and 'script.js` from `.config/cherrytree`

**Comment by txe** [comment]
Closing, it was fixed
