### ISSUE TITLE
Collapse nodes on startup doesn't work if subnode selected

### ISSUE THREAD

**Issue by dreamer320** [giuspen/cherrytree#927]
Running 0.39.3 on Linux.
Have selected Tree 1 > Node status at startup > Collapse all nodes
If I exit the program with a top level node selected, on restart all nodes are collapsed (whether or not the selected node was expanded). The same top node is shown as selected.
However if a subnode is selected on exit, the same subnode (and its parent) are expanded on restart.
The Tree 2 > Expand Node at Mouse Click setting has no effect on this behaviour.
Workaround: Set node_path = 0 in config.

**Comment by txe** [comment]
Hi, 
For example, if `journal`|`2016` should be selected during startup, then, on my machine, I get the left picture. I think it's correct.
Are you saying that you got like on the right picture?

![screenshot](https://user-images.githubusercontent.com/177347/84940755-f5be1d80-b0e8-11ea-8d9f-783ca6b31508.png)

**Comment by dreamer320** [comment]
For your example I get the same left picture as you.
But if I have selected Collapse all Nodes on restart why is the "journal" node not collapsed?
This behaviour seems more consistent with the option "Restore Expanded/Collapsed Status".
However if "journal" is selected on exit (with the node expanded) , then that node will be collapsed on restart. So the collapsing only works if a top level node is selected on exit.

**Comment by txe** [comment]
As you see, the last used node that was selected on the program exist is also selected on the program startup. We show the content of the selected node and we show the selected node on the node panel; not doing the latter would confuse user. In order to show the node, we have to expand its parents in spite of the option to collapse all nodes (actually, the all other nodes are collapsed).

The option "Restore Expanded/Collapsed Status" has the same issue, if we have a node to show and its parents collapsed, we have to expand those nodes.

You already found the way to avoid such behavior: `node_path = 0 in config` 

I don't see how we can improve this situation.
